services:
  config_devel.filestorage_subscriber:
    class: Drupal\config_devel\EventSubscriber\ConfigDevelFileStorageSubscriber
    arguments: ['@config_devel.filestorage', '@config.storage.installer', '@settings', '@config.manager']
    tags:
      - { name: event_subscriber }
  config_devel.filestorage:
    class: Drupal\Core\Config\FileStorage
    factory_service: config_devel.filestorage_factory
    factory_method: get
  config_devel.filestorage_factory:
    class: Drupal\config_devel\Config\FileStorageFactory
    arguments: ['@settings']
  config_devel.config_factory_override:
    class: Drupal\config_devel\Config\ConfigDevelConfigFactoryOverride
    arguments: ['@config.storage.active', '@config_devel.filestorage', '@config.factory', '@settings']
    tags:
      - { name: config.factory.override, priority: -254 }
